// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_play_time_time_limit_mode = "CgkIpLP6wsoMEAIQAw"; // <GPGSID>
        public const string achievement_score_1000k = "CgkIpLP6wsoMEAIQEQ"; // <GPGSID>
        public const string achievement_kill_gamewatch = "CgkIpLP6wsoMEAIQCA"; // <GPGSID>
        public const string achievement_kill_tetris = "CgkIpLP6wsoMEAIQBg"; // <GPGSID>
        public const string achievement_kill_calculator = "CgkIpLP6wsoMEAIQBQ"; // <GPGSID>
        public const string achievement_kill_pager = "CgkIpLP6wsoMEAIQCw"; // <GPGSID>
        public const string achievement_score_250k = "CgkIpLP6wsoMEAIQDw"; // <GPGSID>
        public const string leaderboard_top_score__normal_mode = "CgkIpLP6wsoMEAIQAQ"; // <GPGSID>
        public const string achievement_kill_first_mobile = "CgkIpLP6wsoMEAIQDA"; // <GPGSID>
        public const string achievement_score_50k = "CgkIpLP6wsoMEAIQDQ"; // <GPGSID>
        public const string achievement_kill_tape_player = "CgkIpLP6wsoMEAIQCg"; // <GPGSID>
        public const string achievement_kill_tamagotchi = "CgkIpLP6wsoMEAIQBw"; // <GPGSID>
        public const string achievement_score_500k = "CgkIpLP6wsoMEAIQEA"; // <GPGSID>
        public const string achievement_kill_old_computer = "CgkIpLP6wsoMEAIQBA"; // <GPGSID>
        public const string leaderboard_top_score__time_limit_mode = "CgkIpLP6wsoMEAIQAg"; // <GPGSID>
        public const string achievement_score_100k = "CgkIpLP6wsoMEAIQDg"; // <GPGSID>
        public const string achievement_kill_gameboy = "CgkIpLP6wsoMEAIQCQ"; // <GPGSID>

}

